name: Detekt

on:
  workflow_call:

permissions:
  pull-requests: write
  statuses: write
  checks: write

jobs:
  detekt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest

      - name: Restore gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Run detekt and merge reports
        id: detekt
        continue-on-error: true
        run: ./gradlew detekt reportMerge --continue

      - name: Run report with ReviewDog
        if: steps.detekt.outcome == 'failure'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./build/reports/detekt/merge.xml |
          reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"

      - name: Comment lint check success
        if: steps.detekt.outcome == 'success'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: detekt
          recreate: true
          message: |
            :sparkles: :sparkles: **That's perfect, passed the PR lint check perfectly!** :sparkles: :sparkles:

      - name: Save Result
        if: success() || failure()
        run: echo detekt=${{ steps.detekt.outcome }} >> $GITHUB_ENV
